apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-eshop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-eshop
  template:
    metadata:
      labels:
        app: my-eshop
    spec:
      containers:
      - name: my-eshop-container
        image: udodevprojectacr.azurecr.io/my-eshop:$(Build.BuildId)
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: my-eshop-service
spec:
  selector:
    app: my-eshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
